import React,{useState}from'react';import{createRoot}from'react-dom/client';import'./styles.css';
const artists=[{id:'nova',name:'NOVA CRUEL',type:'Live Electronic Act',city:'Berlin',country:'Germany',genres:['Industrial Techno','Live AV','Warehouse'],fee:'€1.8k–3k',score:94,available:'Jun 28',travel:'EU + UK',rating:'4.9',bio:'Industrial techno duo built for warehouses, late festival slots and high-pressure club rooms.',color:'red'},{id:'mirai',name:'MIRAI UNIT',type:'AV Performer',city:'Tokyo',country:'Japan',genres:['Live Electronic','Experimental','Visuals'],fee:'¥280k–480k',score:89,available:'Jul 12',travel:'Asia + EU',rating:'4.8',bio:'High-detail live electronic and AV performance for theatres, clubs and media festivals.',color:'cyan'},{id:'rain',name:'THE RAIN STATIC',type:'Band',city:'London',country:'United Kingdom',genres:['Post-Punk','Noise Rock','Alternative'],fee:'£900–1.5k',score:87,available:'Fri/Sat',travel:'UK + EU',rating:'4.7',bio:'Sharp post-punk band with strong local draw and fast changeovers.',color:'blue'}];
const nav=['Discover','Search','Book','Inbox','Me'];
function Badge(p){return <span className={'badge '+(p.tone||'')}>{p.children}</span>}
function Shell({view,setView,children}){return <div className='app'><aside><p className='eyebrow'>Global booking OS</p><h1>SoundMatch<br/>Live</h1><p>Swipe-first discovery. Serious booking terms.</p>{nav.map(n=><button onClick={()=>setView(n)} className={view===n?'on':''} key={n}>{n}</button>)}</aside><main><div className='phone'><header><div><p className='micro'>SoundMatch Live</p><h2>{view}</h2></div><button>≡</button></header><section>{children}</section><nav>{nav.map(n=><button onClick={()=>setView(n)} className={view===n?'on':''} key={n}>{n}</button>)}</nav></div></main></div>}
function Card({a}){return <article className='card'><div className='cardtop'><b>MATCH {a.score}%</b><span>Swipe right to match</span></div><div className={'poster '+a.color}><div className='bars'>{Array.from({length:28}).map((_,i)=><i key={i} style={{height:12+((i*13)%45)}}/>)}</div></div><p className='role'>{a.type}</p><h3>{a.name}</h3><p className='loc'>{a.city}, {a.country}</p><div className='chips'>{a.genres.map(g=><span key={g}>{g}</span>)}</div><div className='metrics'><div><small>Fee</small><b>{a.fee}</b></div><div><small>Available</small><b>{a.available}</b></div><div><small>Rating</small><b>{a.rating}</b></div></div><p className='hint'>Tap for EPK · hold to shortlist</p></article>}
function Discover({setView,addMatch}){const[i,setI]=useState(0);const a=artists[i%artists.length];function next(){setI(i+1)}function like(){addMatch(a);next();setView('Inbox')}return <div><div className='filters'><Badge>London · 25 Jun</Badge><Badge tone='blue'>250km</Badge></div><div className='deck'><div className='back one'/><div className='back two'/><Card a={a}/></div><div className='actions'><button className='pass' onClick={next}>Pass</button><button onClick={()=>setI(Math.max(0,i-1))}>Undo</button><button className='interest' onClick={like}>Interested</button></div></div>}
function Inbox({matches,setView}){return <div className='stack'><section className='panel hero'><Badge tone='amber'>New match</Badge><h3>{matches[0]?.name||'No active match yet'}</h3><p>A match opens chat. A real booking still needs structured terms before confirmation.</p><button className='primary' onClick={()=>setView('Book')}>Start booking request</button></section><section className='panel'><h3>Active matches</h3>{(matches.length?matches:artists.slice(1)).map(a=><div className='item' key={a.id}><div><b>{a.name}</b><small>{a.city} · {a.type}</small></div><strong>{a.score}%</strong></div>)}</section></div>}
function Search(){return <div className='stack'><section className='panel'><h3>Search</h3><p>Precision browsing: city, country, genre, budget, availability, verification and map mode.</p></section><section className='panel'><Badge tone='blue'>Venue</Badge><h3>THE CAUSE</h3><p>London, United Kingdom · capacity 850</p><p>Budget £1.2k–3.5k · Club PA, monitors, projector, stage riser</p></section></div>}
function Book(){return <div className='stack'><section className='panel'><Badge tone='green'>Step 2 of 5</Badge><h3>Money + schedule</h3><p>Artist: Nova Cruel</p><p>Venue: The Cause, London</p><p>Date: Fri 28 Jun 2026</p><p className='accent'>Fee offer: £2,200 GBP</p></section><section className='panel chat'><h3>Chat</h3><p>Can you confirm stereo DI and a safe riser?</p><p className='buyer'>Yes. DI, riser and 30% deposit confirmed.</p></section></div>}
function Me(){return <div className='stack'><section className='panel epk'><div className='poster red'/><h3>NOVA CRUEL</h3><p>Industrial techno duo built for warehouses, late festival slots and high-pressure club rooms.</p><p className='accent'>Fee €1.8k–3k · Available Jun–Sep · Travel EU / UK / US</p></section></div>}
function App(){const[view,setView]=useState('Discover');const[matches,setMatches]=useState([]);const addMatch=a=>setMatches(m=>m.find(x=>x.id===a.id)?m:[a,...m]);let screen=view==='Discover'?<Discover setView={setView} addMatch={addMatch}/>:view==='Search'?<Search/>:view==='Book'?<Book/>:view==='Inbox'?<Inbox matches={matches} setView={setView}/>:<Me/>;return <Shell view={view} setView={setView}>{screen}</Shell>}
createRoot(document.getElementById('root')).render(<App/>);
